CREATE DATABASE JOINS;
USE JOINS;

CREATE TABLE CLIENTE (
    CODCLI CHAR(3) NOT NULL PRIMARY KEY,
    NOME VARCHAR(40) NOT NULL,
    ENDERECO VARCHAR(50) NOT NULL,
    CIDADE VARCHAR(20) NOT NULL,
    ESTADO CHAR(2) NOT NULL,
    CEP CHAR(9) NOT NULL
);

CREATE TABLE VENDA (
    DUPLIC CHAR(6) NOT NULL PRIMARY KEY,
    VALOR DECIMAL(10,2) NOT NULL,
    VENCTO DATE NOT NULL,
    CODCLI CHAR(3) NOT NULL,
    FOREIGN KEY (CODCLI) REFERENCES CLIENTE(CODCLI)
);

INSERT INTO CLIENTE VALUES (
    '250',
    'BANCO BARCA S/A',
    'R. VITO, 34',
    'SAO SEBASTIAO',
    'CE',
    '62380-000'
);

INSERT INTO CLIENTE VALUES (
    '170',
    'POSTO BRASIL LTDA',
    'AV.IMPERIO, 85',
    'GUAGIRUS',
    'BA',
    '42837-000'
);

INSERT INTO CLIENTE VALUES (
    '820',
    'MECANICA SAO PAULO',
    'R. DO MACUCO, 99',
    'SANTO ANTONIO',
    'ES',
    '29810-020'
);

INSERT INTO VENDA VALUES (
    '230002',
    1300.00,
    '2001-06-10',
    '250'
);

INSERT INTO VENDA VALUES (
    '230099',
    1000.00,
    '2002-10-02',
    '820'
);

INSERT INTO VENDA VALUES (
    '997818',
    1000.00,
    '2001-11-11',
    '170'
);
-- ================================================================
-- CONSULTAS
-- =================================================================

-- NOME CLIENTE E DUPLIC
SELECT CLIENTE.NOME, VENDA.DUPLIC
FROM CLIENTE, VENDA
WHERE CLIENTE.CODCLI = VENDA.CODCLI;

-- CONSULTA COM INNER JOIN
SELECT VENDA.DUPLIC, CLIENTE.NOME
FROM CLIENTE INNER JOIN VENDA
ON CLIENTE.CODCLI = VENDA.CODCLI
ORDER BY CLIENTE.NOME;

SELECT VENDA.DUPLIC, CLIENTE.NOME, CLIENTE.CIDADE
FROM CLIENTE INNER JOIN VENDA
ON CLIENTE.CODCLI = VENDA.CODCLI
ORDER BY CLIENTE.NOME;

SELECT CLIENTE.NOME, COUNT(*) AS QTDE
FROM CLIENTE INNER JOIN VENDA
ON CLIENTE.CODCLI = VENDA.CODCLI
GROUP BY CLIENTE.NOME;

SELECT CLIENTE.NOME, SUM(VENDA.VALOR) AS TOTAL_VENDAS
FROM CLIENTE INNER JOIN VENDA
ON CLIENTE.CODCLI = VENDA.CODCLI
GROUP BY CLIENTE.NOME
ORDER BY TOTAL_VENDAS DESC;

SELECT CLIENTE.NOME, VENDA.DUPLIC, MAX(VENDA.VALOR) AS MAIOR_VENDA
FROM CLIENTE INNER JOIN VENDA
ON CLIENTE.CODCLI = VENDA.CODCLI
GROUP BY VENDA.DUPLIC;

-- ===============================================================
-- TABELA NOVA PARA USO DE INNER JOIN, LEFT JOIN E RIGHT JOIN
-- ===============================================================

CREATE TABLE EX (
    NOME VARCHAR(100)
);

CREATE TABLE FX (
    NOME VARCHAR(100)
);

INSERT INTO EX VALUES
("BRUNO"),
("FERNANDO"),
("BIANCA"),
("MARIA"),
("JOAO");

INSERT INTO FX VALUES
("BRUNO"),
("FERNANDO"),
("CARLOS"),
("PAULO"),
("JULIA");

-- INNER JOIN
SELECT EX.NOME AS NOME_EX, FX.NOME AS NOME_FX
FROM EX INNER JOIN FX
ON EX.NOME = FX.NOME;

SELECT EX.NOME, FX.NOME
FROM EX AS EX
LEFT JOIN FX AS FX
ON EX.NOME = FX.NOME;

-- =============================================================
-- UNION
-- =============================================================

SELECT EX.NOME AS NOME_EX
FROM EX
UNION
SELECT FX.NOME AS NOME_FX
FROM FX;

SELECT EX.NOME AS NOME_EX
FROM EX AS EX
RIGHT JOIN FX AS FX
ON EX.NOME = FX.NOME;

SELECT CLIENTE.NOME, VENDA.VENCTO
FROM CLIENTE INNER JOIN VENDA
ON CLIENTE.CODCLI = VENDA.CODCLI
WHERE YEAR(VENDA.VENCTO) = 2002 AND MONTH(VENDA.VENCTO) = 10
ORDER BY VENDA.VENCTO;