-- CRIANDO O BANCO DE DADOS
CREATE DATABASE IF NOT EXISTS SOLAR;
USE SOLAR;

-- TABELA CLIENTES
CREATE TABLE IF NOT EXISTS CLIENTES (
    COD_CLIENTE INT NOT NULL AUTO_INCREMENT,   -- CÓDIGO DO CLIENTE
    NOME_CLIENTE VARCHAR(100),                 -- NOME DO CLIENTE
    CPF VARCHAR(14) NOT NULL,                  -- CPF DO CLIENTE
    ENDERECO VARCHAR(100),                     -- ENDEREÇO DO CLIENTE
    CELULAR VARCHAR(19),                       -- CELULAR DO CLIENTE
    PRIMARY KEY (COD_CLIENTE)                  -- CHAVE PRIMÁRIA
);

-- TABELA FORNECEDOR
CREATE TABLE IF NOT EXISTS FORNECEDOR (
    COD_FORNECEDOR INT NOT NULL AUTO_INCREMENT, -- CÓDIGO DO FORNECEDOR
    NOME_FORNECEDOR VARCHAR(100),               -- NOME DO FORNECEDOR
    CNPJ VARCHAR(18) NOT NULL,                  -- CNPJ DO FORNECEDOR
    ENDERECO VARCHAR(100),                      -- ENDEREÇO DO FORNECEDOR
    CELULAR VARCHAR(19),                        -- CELULAR DO FORNECEDOR
    PRIMARY KEY (COD_FORNECEDOR)                -- CHAVE PRIMÁRIA
);

-- TABELA PRODUTO
CREATE TABLE IF NOT EXISTS PRODUTO (
    COD_PRODUTO INT NOT NULL AUTO_INCREMENT,    -- CÓDIGO DO PRODUTO
    NOME_PRODUTO VARCHAR(100),                  -- NOME DO PRODUTO
    VALOR DECIMAL(10,2),                        -- VALOR DO PRODUTO
    DESCRICAO VARCHAR(100),                     -- DESCRIÇÃO DO PRODUTO
    QUANTIDADE_PRODUTO INT,                     -- QUANTIDADE EM ESTOQUE
    COD_FORNECEDOR INT NOT NULL,                -- CÓDIGO DO FORNECEDOR
    PRIMARY KEY (COD_PRODUTO),                  -- CHAVE PRIMÁRIA
    FOREIGN KEY (COD_FORNECEDOR) REFERENCES FORNECEDOR(COD_FORNECEDOR)
);

-- TABELA VENDA
CREATE TABLE IF NOT EXISTS VENDA (
    COD_VENDA INT NOT NULL AUTO_INCREMENT,      -- CÓDIGO DA VENDA
    COD_PRODUTO INT NOT NULL,                   -- PRODUTO VENDIDO
    COD_FORNECEDOR INT NOT NULL,                -- FORNECEDOR DO PRODUTO
    PRIMARY KEY (COD_VENDA),                    -- CHAVE PRIMÁRIA
    FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO(COD_PRODUTO),
    FOREIGN KEY (COD_FORNECEDOR) REFERENCES FORNECEDOR(COD_FORNECEDOR)
);

-- TABELA DEPARTAMENTO
CREATE TABLE IF NOT EXISTS DEPARTAMENTO (
    COD_DEPARTAMENTO INT NOT NULL AUTO_INCREMENT,  -- CÓDIGO DO DEPARTAMENTO
    NOME_DEPARTAMENTO VARCHAR(100) NOT NULL,       -- NOME DO DEPARTAMENTO
    PRIMARY KEY (COD_DEPARTAMENTO)                 -- CHAVE PRIMÁRIA
);

-- TABELA FUNCIONARIOS (original)
CREATE TABLE IF NOT EXISTS FUNCIONARIOS (
    COD_FUNCIONARIO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,   -- CÓDIGO DO FUNCIONÁRIO
    NOME_FUNCIONARIO VARCHAR(100) NOT NULL,                    -- NOME DO FUNCIONÁRIO
    CARGO VARCHAR(100),                                        -- CARGO DO FUNCIONÁRIO
    CPF_FUNCIONARIO VARCHAR(14),
    ENDERECO_FUNCIONARIO VARCHAR(100),
    DATA_NASCIMENTO DATETIME NOT NULL,
    DATA_ADMISSAO DATETIME NOT NULL,
    DATA_RESCISAO DATETIME NOT NULL,
    SALARIO DECIMAL(10,2),                                     -- SALÁRIO DO FUNCIONÁRIO
    COD_DEPARTAMENTO INT NOT NULL,                              -- CÓDIGO DO DEPARTAMENTO
    FOREIGN KEY (COD_DEPARTAMENTO) REFERENCES DEPARTAMENTO(COD_DEPARTAMENTO)
);

-- CONSULTAR TABELA FUNCIONARIOS
SELECT * FROM FUNCIONARIOS;

-- ALTERAÇÕES EM TABELAS

-- 1️⃣ ADICIONA COLUNA SEXO
ALTER TABLE FUNCIONARIOS
ADD COLUMN SEXO CHAR(1);

-- 2️⃣ REMOVE COLUNA SEXO
ALTER TABLE FUNCIONARIOS
DROP COLUMN SEXO;

-- 3️⃣ RENOMEIA A TABELA PARA EMPREGADO
ALTER TABLE FUNCIONARIOS
RENAME TO EMPREGADO;

-- 4️⃣ MANTÉM A COLUNA COMO CPF_FUNCIONARIO
-- (nenhuma alteração de nome necessária)

-- 5️⃣ ADICIONA COLUNA ESTADO COM VALOR PADRÃO
ALTER TABLE EMPREGADO
ADD COLUMN ESTADO CHAR(2) DEFAULT 'MG';

-- -------------------------
-- OPÇÃO 1: PK SIMPLES (COD_FUNCIONARIO AUTO_INCREMENT) ✅
-- Mantemos COD_FUNCIONARIO como PK, CPF_FUNCIONARIO apenas NOT NULL
-- ALTER TABLE EMPREGADO MODIFY CPF_FUNCIONARIO INT NOT NULL;

-- -------------------------
-- OPÇÃO 2: PK COMPOSTA (remover AUTO_INCREMENT) ⚠️
-- Se quiser chave composta (COD_FUNCIONARIO, CPF_FUNCIONARIO), faça assim:
ALTER TABLE EMPREGADO MODIFY COD_FUNCIONARIO INT NOT NULL;
ALTER TABLE EMPREGADO MODIFY CPF_FUNCIONARIO INT NOT NULL;
ALTER TABLE EMPREGADO DROP PRIMARY KEY;
ALTER TABLE EMPREGADO ADD PRIMARY KEY (COD_FUNCIONARIO, CPF_FUNCIONARIO);

-- --------------------------------------------------------------------------------

CREATE TABLE TIPO_PRODUTOS (
    COD_TIPO_PRODUTO INT AUTO_INCREMENT NOT NULL,
    TIPO_PRODUTO VARCHAR(225) NOT NULL,
    PRIMARY KEY (COD_TIPO_PRODUTO),
    INDEX IDX_TIPO_PRODUTO (TIPO_PRODUTO)
);
